### PR TITLE
Update mbed-ls to work with >v1.3.5

### LINKED ISSUE #79: Not compatible with mbed-ls >=1.3.0?  (use of manufacture_ids)
I'm on Windows 10 with mbed-ls version 1.3.4 installed.

looks like mbed-flasher is relying on a method in mbed_lstools (mbed-ls) that went away in mbded-ls v1.3.0.

the manufacture_ids array went away.  After 1.3, now to get the ids, use list_manufacture_ids().  I'm not savvy enough in python to make the needed change.  

Using a test script that relies on update_supported_targets, results in this. 
 
```
   File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\test\GenericTestcase.py", line 33, in <module>
    flasher = Flash()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flash.py", line 42, in __init__
    self.supported_targets = self.__update_supported_targets()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flash.py", line 65, in __update_supported_targets
    supported_targets = flasher.get_supported_targets()
  File "C:\Users\maclob01\Documents\mbed-os-5\nanostack-rf-driver-tester.git\mbed-flasher\mbed_flasher\flashers\FlasherMbed.py", line 60, in get_supported_targets
    return sorted(set(mbeds.manufacture_ids.values()))
AttributeError: 'MbedLsToolsWin7' object has no attribute 'manufacture_ids'

```

Downgrading mbed-ls to 1.2.16 works, but this looses the new targets that were added after that.  

Please update!

### PR DESCRIPTION
**Pull request by jupe**
## Status
**READY**

## Description 
Brings mbed-ls >=v1.3.5 support.
**Note:** doesn't work anymore with older versions of mbed-ls

## Related PR:
* fixes #79 
* https://github.com/ARMmbed/mbed-ls/issues/277
* https://github.com/ARMmbed/mbed-ls/pull/280
* IOTMORF-1657 (public mbed-ls API missing to fetch supported target list)

### CODE REVIEW

**Comment by YifeiZuo01** [comment]
``` File "C:\Jenkins\ws\mbed-flasher_PR-80-6DBC3QYY2VB4FPBKQLUJCWX3MRRUU\mbed-flasher\mbed_flasher\flashers\FlasherMbed.py", line 66, in get_supported_targets
08:08:34 [windows]     list_supported_targets = sorted(set(mbeds.plat_db._dbs.values()[0].values()))
08:08:34 [windows] TypeError: 'odict_values' object does not support indexing
```

**Comment by YifeiZuo01** [comment]
able to reproduce locally, so I guess not device problem

**Comment by YifeiZuo01** [comment]
Ï guess this is the [reason](https://github.com/ARMmbed/mbed-flasher/blob/96a54229fe21534ba3713bfc8070522452d11577/mbed_flasher/flashers/FlasherMbed.py#L76)

**Comment by YifeiZuo01** [comment]
yes, that's the unicode problem.

**Comment by YifeiZuo01** [comment]
why windows py2 didn't fail

File: mbed_flasher/flashers/FlasherMbed.py [hunk 1]
```diff
@@ -57,7 +57,16 @@ def get_supported_targets():
...
         """
         mbeds = mbed_lstools.create()
-        return sorted(set(mbeds.manufacture_ids.values()))
+        try:
+            # this works for <v1.3.0
+            list_supported_targets = sorted(set(mbeds.manufacture_ids.values()))
+        except AttributeError:
+            try:
+                # this should works for >=v1.3.0
+                list_supported_targets = sorted(set(list(mbeds.plat_db._dbs.values())[0].values()))
```
Comment (theotherjimmy) [inline mbed_flasher/flashers/FlasherMbed.py]: Please don't use private variables (prefixed with a `_`). Instead you can use `plat_db.items()`

File: mbed_flasher/flashers/FlasherMbed.py [hunk 2]
```diff
@@ -63,7 +63,7 @@ def get_supported_targets():
         except AttributeError:
             try:
                 # this should works for >=v1.3.0
-                list_supported_targets = sorted(set(list(mbeds.plat_db._dbs.values())[0].values()))
+                list_supported_targets = sorted(set(list(mbeds.plat_db.items().values())[0].values()))
```
Comment (theotherjimmy) [inline mbed_flasher/flashers/FlasherMbed.py]: That probably does not do what you want. That'll always produce an `AttributeError` when trying to get the `values` method on the `items` iterator.

File: mbed_flasher/flashers/FlasherMbed.py (hunk 1 above)
Comment (jupe) [reply mbed_flasher/flashers/FlasherMbed.py]: is this only way to get names for now until we have better API for this?

Comment (theotherjimmy) [reply mbed_flasher/flashers/FlasherMbed.py]: Yes.

File: mbed_flasher/flashers/FlasherMbed.py (hunk 2 above)
Comment (jupe) [reply mbed_flasher/flashers/FlasherMbed.py]: ouch true. need something else then..

Comment (theotherjimmy) [reply mbed_flasher/flashers/FlasherMbed.py]: You want:
```python
sorted(set(name for id, name in mbeds.plat_db.items()))

Comment (jupe) [reply mbed_flasher/flashers/FlasherMbed.py]: thanks, that was exactly what I looked for :)

Comment (theotherjimmy) [reply mbed_flasher/flashers/FlasherMbed.py]: I'm actually considering making that the official API. That has the advantage that you should be able to correctly use mocked targets.

**Comment by jupe** [comment]
@theotherjimmy seems that this is not enough; also another api is not there anymore even readme mention about it still: `get_mbed_com_port`. Probably it was dropped during same time.. that why CI was not happy:
```
Instance of 'MbedLsToolsWin7' has no 'get_mbed_com_port' member
Instance of 'MbedLsToolsLinuxGeneric' has no 'get_mbed_com_port' member
Instance of 'MbedLsToolsDarwin' has no 'get_mbed_com_port' member
```

**Comment by theotherjimmy** [comment]
@jupe I don't recall dropping that method.

**Comment by theotherjimmy** [comment]
@jupe You should be able to get the comm port from the "serial_port" member of the return value of `list_mbeds`

**Comment by jupe** [comment]
it could but is there some reason why original API could not be there anymore ?

**Comment by theotherjimmy** [comment]
I can add it back to mbed-ls, and I will. OTOH, there already exists a release of mbed-ls without it, and I will be adding it back _as a deprecated function_.

**Comment by theotherjimmy** [comment]
How did you find the `tid` parameter that you passed in?

**Comment by jupe** [comment]
> How did you find the tid parameter that you passed in?

from previous mbed-ls call which results was stored to application cache..

**Comment by theotherjimmy** [comment]
> from previous mbed-ls call which results was stored to application cache..

Which already contains this data....

**Comment by jupe** [comment]
its just one use case. Individual user probably doesn't want to add serial_port either mount_point when calling `mbed-flash` for flashing device...

**Comment by theotherjimmy** [comment]
@jupe I don't undestand your comment. Why would you need to add those parameters when mbed-ls can get them for you?

**Comment by jupe** [comment]
exactly - we doesn't add those because mbed-ls gives them for us. Reason why we uses `get_mbed_com_port()` originally was that it was much faster than listing all devices. Could be that latest release is fast enough so we could fetch all data every time, but it sounds that @bridadan mentioned `platform_name_filters` approach would be most efficient for this..

File: mbed_flasher/flashers/FlasherMbed.py [hunk 3]
```diff
@@ -57,7 +57,17 @@ def get_supported_targets():
         Load target mapping information
         """
         mbeds = mbed_lstools.create()
-        return sorted(set(mbeds.manufacture_ids.values()))
+        try:
+            # this works for <v1.3.0
+            list_supported_targets = sorted(set(mbeds.manufacture_ids.values()))
```
Comment (jupe) [inline mbed_flasher/flashers/FlasherMbed.py]: maybe we should drop this part away

**Comment by jupe** [comment]
@bridadan @theotherjimmy could you review this also. It looks that we have to create flasher release without IOTMORF-1657 because this is blocking already so many things.

**Comment by jupe** [comment]
> Why is mbedls run only on windows?

good question :). I’m not sure but I guess it related to issue where serial port might change during device is mounting back. I think that was some corner case problem in windows which might happen when there is multiple devices connected to host and we are flashing parallel.. Maybe @VeliMattiLahtela remember this?

File: mbed_flasher/common.py [hunk 4]
```diff
@@ -56,10 +56,15 @@ def check_points_unchanged(self, target):
...
-            mbeds = mbed_lstools.create()
-            if target['serial_port'] != mbeds.get_mbed_com_port(target['target_id']):
-                new_target['serial_port'] = mbeds.get_mbed_com_port(target['target_id'])
-
+            mbedls = mbed_lstools.create()
+            mbeds = mbedls.list_mbeds(filter_function=
+                                      lambda m: m['target_id'] == target['target_id'])
+            if len(mbeds) == 1:
+                if target['serial_port'] != mbeds[0]['serial_port']:
+                    new_target['serial_port'] = mbeds[0]['serial_port']
```
Comment (bridadan) [inline mbed_flasher/common.py]: You really can just set `new_target` to `mbeds[0]` if you want. I'd suggest doing that instead of doing selective updates.

That is of course you're doing something strange that requires the selective update 😛

Comment (jupe) [reply mbed_flasher/common.py]: I think we have to do other refactoring as well - so lets keep this for now..

File: setup.py [hunk 5]
```diff
@@ -54,7 +53,7 @@ def read(fname):
           "console_scripts": ["mbedflash=mbed_flasher:mbedflash_main",],
       },
       install_requires=[
-          "mbed-ls==1.2.16" if "win" in sys.platform else ["mbed-ls==1.2.14"],
+          "mbed-ls==1.3.5",
```
Comment (YifeiZuo01) [inline setup.py]: > Brings mbed-ls >=v1.3.5 support.
Hardcode `==1.3.5` ?

Comment (jupe) [reply setup.py]: for now we have to hard code it because there is still workaround for IOTMORF-1657 and there is no API tests for https://github.com/ARMmbed/mbed-ls/pull/280. Implementation point of view it should be compatible with mbed-ls 1.x.x versions so when above issues is fixed we can create patch release with something like `>=1.3.6`
